# Generated by Django 6.1.1 on 2026-10-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=30)),
                ('release_year', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('rating', models.FloatField()),
            ],
        ),
    ]
